### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by rikschennink** [Sidstumple/minor-CSStotherescue#2]
Ondanks dat het er tof uit ziet dat de pagina geblurred wordt. Kan mijn iMac (in een grotere view) de animatie bijna niet aan :(

**Comment by rikschennink** [comment]
De links in het menu mogen van mij ook nog wel wat groter

**Comment by Sidstumple** [comment]
Ik heb de blur veranderd in een donkere laag, dit zou moeten zorgen dat de animatie minder zwaar is. De menu links zijn nu 1em, ik zou ze wel groter kunnen maken maar ik denk dat er genoeg padding tussen zit om zelfs met dikke vingers ze nog makkelijk te kunnen raken.
