### ISSUE TITLE
Rating is een beetje mini

### ISSUE THREAD

**Issue by rikschennink** [Sidstumple/minor-CSStotherescue#4]
Die moet wel iets groter :) 

Ik kan niet zien welk item ik selecteert heb. Je zou de :checked selector in combinatie met de sibling selector kunnen gebruiken om de smileys te stijlen aan de hand van de geselecteerde checkbox (dit kan bij de stay-logged-in checkbox ook nog nuttig zijn). Misschien is het zelfs mogelijk de "er is nog geen radio button geselecteerd" state te stylen...

**Comment by Sidstumple** [comment]
Yes ik heb hem aangepast en vooral een stuk groter gemaakt!
